### ISSUE TITLE
sql文件还存在吗？

### ISSUE THREAD

**Issue by xiaonian233** [fzcoder/animeisland-server#1]
老哥你好，对这个项目比较感兴趣，根据实体类创建了一些表，但是如果可以的话不知道能拿到原版sql文件吗？谢谢

**Comment by zheenfun** [comment]
很抱歉没有及时看到你的issue

目前项目已经重构，sql脚本请参考README.md

项目目前还存在一些bug和未完成的功能，切勿用于生产环境，另外本项目仅适用于局域网，如需要公网部署，请自行实现权限认证等相关功能

- Web端地址：[https://github.com/fzcoder/animeisland-web](https://github.com/fzcoder/animeisland-web)
- 后台管理端地址：[https://github.com/fzcoder/animeisland-admin](https://github.com/fzcoder/animeisland-admin)

**Comment by xiaonian233** [comment]
非常感谢非常感谢
